mode:
  - train
  - eval

model_types:
  - rnn
#  - transformer
#  - lnn

global_params:
  train_symbols:
  - "atnf"
  #- "biaf"
  - "bivi"
  - "cycc"
  - "vtak"
  target_symbol: "atnf"
  log_splits: False
  global_to_target_split: 0.5

rnn:
  batch_size: 10
  hidden_size: 16
  seq_len: 50
  dropout: 0.2
  num_layers: 2
  num_outputs: 3

rnn_trainer:
  epochs: 300
  lr: 5.e-6
  fine_tune_lr_ratio: 0.1
  optimizer:
    name: "adam"
    config:
      eps: 1.e-8
      betas: [0.9, 0.99]
      weight_decay: 1.e-3
  scheduler:
    name: 'plateau'
  criterion:
    name: "ce"

lnn:
  batch_size: 16
  n_layers: 6
  hidden_size: 32
  activation: sigmoid
  seq_len: 20
  output_size: 3

lnn_trainer:
  fine_tune_lr_ratio: 0.1
  epochs: 200
  lr: 1.e-3
  optimizer: 
    name: "adam"
    config:
      eps: 1.e-8
      betas: [0.9, 0.99]
      weight_decay: 1.e-3
  scheduler:
    name: 'plateau'
  criterion:
    name: 'ce'

transformer:
  batch_size: 128
  seq_len: 20
  model_dim: 64
  ignore_cols:
    - 0
  time_idx:
    - 6
    - 7
    - 8
  fc_dim: 512
  fc_dropout: 0.1
  mlp_dim: 2048
  mlp_dropout: 0.3
  n_frequencies: 64
  num_encoders: 3
  num_heads: 8
  num_lstm_layers: 2
  lstm_dim: 256
  pretrained_t2v: data/t2v_weights/t2v_n64_mlp1024_lr6.310e-05.pth

transformer_trainer:
  epochs: 200
  lr: 1.e-5
  fine_tune_lr_ratio: 0.1
  optimizer:
    name: "adam"
    config:
      eps: 1.e-8
      betas: [0.9, 0.99]
      weight_decay: 1.e-3
  scheduler:
    name: 'plateau'
  criterion:
    name: "cb_focal"  # Class Balanced Focal Loss
  cbf_gamma: 1.0
  cbf_beta: 0.99
