mode:
  - train
  - eval

model_types: 
  - rnn
  #- transformer
  #- lnn

rnn:
  batch_size: 10
  num_layers: 1

lnn:
  batch_size: 10
  n_layers: 6
  hidden_size: 32
  


transformer:
  batch_size: 10
