mode:
  - train
  - eval

model_types:
  - rnn
  #- transformer
  #- lnn

global_params:
  train_symbols: 
  - "atnf"
  #- "biaf"
  - "bivi"
  - "cycc"
  - "vtak"
  target_symbol: "atnf"
  log_splits: False
  global_to_target_split: 0.5

rnn:
  batch_size: 10
  hidden_size: 16
  seq_len: 50
  dropout: 0.2
  num_layers: 2
  num_outputs: 3

rnn_trainer:
  epochs: 10
  lr: 5.e-6
  fine_tune_lr_ratio: 0.1
  optimizer: "adam"
  scheduler: "plateau"
  criterion: "cb_focal"  # Class Balanced Focal Loss

lnn:
  batch_size: 10

lnn_trainer:
  epochs: 10
  lr: 5.e-6
  optimizer: "adam"
  scheduler: "plateau"
  criterion: "cb_focal"  # Class Balanced Focal Loss

transformer:
  batch_size: 64
  seq_len: 30
  model_dim: 64
  time_idx:
    - 0
    - 6
    - 7
    - 8
  fc_dim: 1024
  fc_dropout: 0.3
  n_frequencies: 16
  num_encoders: 4
  num_heads: 4
  num_lstm_layers: 2
  lstm_dim: 128

transformer_trainer:
  epochs: 10
  lr: 5.e-6
  optimizer: "adam"
  scheduler: "plateau"
  criterion: "cb_focal"  # Class Balanced Focal Loss
