params:
  buy_percent: 0.333
  sell_percent: 0.333
  hold_percent: 0.333
  seed: 1984

trainer:
  global_to_target_split: 0.82
  batch_size: 20
  seq_len: 10
  epochs: 1
  lr: 5.e-6
  fine_tune_lr_ratio: 0.1
  optimizer:
    name: "adam"
    config:
      eps: 1.e-8
      betas: [0.9, 0.99]
      weight_decay: 1.e-3
  scheduler:
    name: 'plateau'
  criterion:
    name: "ce"
