params:
  hidden_size: 24
  dropout: 0.21
  num_layers: 2
  num_outputs: 3

trainer:
  global_to_target_split: 0.82
  batch_size: 20
  seq_len: 75
  epochs: 100
  lr: 5.e-6
  fine_tune_lr_ratio: 0.1
  optimizer:
    name: "adam"
    config:
      eps: 1.e-8
      betas: [0.9, 0.99]
      weight_decay: 1.e-3
  scheduler:
    name: 'plateau'
  criterion:
    name: "ce"
