run_models:
  - baseline_uniform
  - baseline_tuned
  - rnn
  - transformer
  - lnn
  - lnn_cfc

training_params:
  train_symbols:
  - "atnf"
  - "bivi"
  - "cycc"
  - "vtak"
  - "spx"
  target_symbol: "atnf"
  log_splits: False

overrides:
  global_to_target_split: 0.25
