run_models:
  - rnn
  - transformer
  - lnn
  - lnn_cfc

training_params:
  train_symbols:
  - "atnf"
  - "bivi"
  - "cycc"
  - "vtak"
  - "spx"
  target_symbol: "atnf"
  log_splits: False

overrides:
  criterion:
    name: ce
